flask:
env:
  test
log_level:
  INFO
language:
  zh
web:
  ip: 0.0.0.0
  port: 5000
minio:
  dev:
    host: 121.40.49.158
    port: 9000
    username: zhaoxinyuan996
    password: 996yeszxy
    secure: false
  test:
    host: 127.0.0.1
    port: 9000
    username: zhaoxinyuan996
    password: 996yeszxy
    secure: false
  prod:
    host: 121.40.49.158
    port: 9000
    access_key:
    secret_key:
    secure:
db:
  dev:
    host: 121.40.49.158
    port: 5432
    db_name: flag_test
    user: postgres
    passwd: awesomezxy
    max_connection_num: 100
    max_overflow: 50
  test:
    host: 127.0.0.1
    port: 5432
    db_name: flag_test
    user: postgres
    passwd: awesomezxy
    max_connection_num: 100
    max_overflow: 50
  prod:
    host: 121.40.49.158
    port: 5432
    db_name: flag_test
    user: postgres
    passwd: awesomezxy
    max_connection_num: 100
    max_overflow: 50
